trigger:
  branches:
    include:
      - main

parameters:
- name: buildImage
  displayName: 'Build Docker image?'
  type: boolean
  default: true

variables:
  dockerImage:  m1328/discord-movie-bot:latest

stages:
- stage: Test
  displayName: 'Run tests'
  jobs:
    - job: PyTest
      displayName: 'Install deps, run pytest and black'
      pool:
         name: 'discord-bot'
      steps:
        - checkout: self

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'

        - script: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'

        - script: |
            source venv/bin/activate
            pytest tests
          displayName: 'Run tests with pytest'

        - script: |
            source venv/bin/activate
            black --check src
          displayName: 'Run black style check'

- stage: Docker
  displayName: 'Build and push Docker image'
  condition: and(succeeded(), eq('${{ parameters.buildImage }}', true))
  jobs:
    - job: DockerBuild
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self

        - task: Docker@2
          inputs:
            command: 'buildAndPush'
            containerRegistry: 'DockerHubConnection'
            repository: 'm1328/discord-bot'
            Dockerfile: 'Dockerfile'
            tags: |
              latest
